import { Migration } from '@mikro-orm/migrations';

const TENANT_SCOPED_AUTH_TABLES = [
  'user_invitations',
  'auth_sessions',
] as const;

export class Migration20260802174750_tenant_provisioning extends Migration {
  override up(): void | Promise<void> {
    // Generated by MikroORM from the entity metadata.
    this.addSql(
      `create table "users" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "email" text not null, "display_name" text null, "password_hash" text null, "role" text not null default 'tenant_admin', "status" text not null default 'invited', "email_verified_at" timestamptz null, "activated_at" timestamptz null, "suspended_at" timestamptz null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), primary key ("id"));`,
    );
    this.addSql(
      `alter table "users" add constraint "users_tenant_id_id_unique" unique ("tenant_id", "id");`,
    );
    this.addSql(
      `alter table "users" add constraint "users_email_unique" unique ("email");`,
    );

    this.addSql(
      `create table "auth_sessions" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "user_id" uuid not null, "token_hash" varchar(64) not null, "expires_at" timestamptz not null, "last_seen_at" timestamptz not null default now(), "revoked_at" timestamptz null, "created_at" timestamptz not null default now(), primary key ("id"));`,
    );
    this.addSql(
      `create index "auth_sessions_user_expiry_lookup" on "auth_sessions" ("tenant_id", "user_id", "expires_at");`,
    );
    this.addSql(
      `alter table "auth_sessions" add constraint "auth_sessions_tenant_token_unique" unique ("tenant_id", "token_hash");`,
    );

    this.addSql(
      `create table "user_invitations" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "user_id" uuid not null, "token_hash" varchar(64) not null, "expires_at" timestamptz not null, "accepted_at" timestamptz null, "revoked_at" timestamptz null, "created_at" timestamptz not null default now(), primary key ("id"));`,
    );
    this.addSql(
      `alter table "user_invitations" add constraint "user_invitations_tenant_token_unique" unique ("tenant_id", "token_hash");`,
    );
    this.addSql(
      `create unique index user_invitations_active_user_unique on user_invitations (tenant_id, user_id) where accepted_at is null and revoked_at is null;`,
    );

    this.addSql(
      `alter table "users" add constraint "users_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on delete restrict;`,
    );
    this.addSql(
      `alter table "users" add constraint "users_email_normalized" check (email = lower(btrim(email)) and email ~ '^[^@[:space:]]+@[^@[:space:]]+$');`,
    );
    this.addSql(
      `alter table "users" add constraint "users_display_name_not_blank" check (display_name is null or btrim(display_name) <> '');`,
    );
    this
      .addSql(`alter table "users" add constraint "users_status_shape_valid" check (
        (
          status = 'invited'
          and password_hash is null
          and activated_at is null
          and suspended_at is null
        )
        or
        (
          status = 'active'
          and display_name is not null
          and password_hash is not null
          and activated_at is not null
          and suspended_at is null
        )
        or
        (
          status = 'suspended'
          and display_name is not null
          and password_hash is not null
          and activated_at is not null
          and suspended_at is not null
        )
      );`);
    this.addSql(
      `alter table "users" add constraint "users_role_check" check ("role" in ('tenant_admin'));`,
    );
    this.addSql(
      `alter table "users" add constraint "users_status_check" check ("status" in ('invited', 'active', 'suspended'));`,
    );
    this.addSql(
      `create trigger users_touch_updated_at before update on users for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "auth_sessions" add constraint "auth_sessions_user_fk" foreign key ("tenant_id", "user_id") references "users" ("tenant_id", "id") on delete cascade;`,
    );
    this.addSql(
      `alter table "auth_sessions" add constraint "auth_sessions_token_hash_format" check (token_hash ~ '^[0-9a-f]{64}$');`,
    );
    this.addSql(
      `alter table "auth_sessions" add constraint "auth_sessions_expiry_valid" check (expires_at > created_at);`,
    );

    this.addSql(
      `alter table "user_invitations" add constraint "user_invitations_user_fk" foreign key ("tenant_id", "user_id") references "users" ("tenant_id", "id") on delete cascade;`,
    );
    this.addSql(
      `alter table "user_invitations" add constraint "user_invitations_token_hash_format" check (token_hash ~ '^[0-9a-f]{64}$');`,
    );
    this.addSql(
      `alter table "user_invitations" add constraint "user_invitations_expiry_valid" check (expires_at > created_at);`,
    );
    this.addSql(
      `alter table "user_invitations" add constraint "user_invitations_resolution_valid" check (accepted_at is null or revoked_at is null);`,
    );

    // PostgreSQL-only RLS policies and grants.
    // `users` deliberately has no RLS: login finds the globally unique email
    // before the application knows which tenant context to establish.
    for (const table of TENANT_SCOPED_AUTH_TABLES) {
      this.addSql(`
        alter table ${table} enable row level security;
        alter table ${table} force row level security;
        create policy ${table}_tenant_isolation on ${table}
        using (tenant_id = app.current_tenant_id())
        with check (tenant_id = app.current_tenant_id());
      `);
    }

    this.addSql(`
      grant usage on schema public, app to lodgekeeper_provisioner;
      grant execute on function app.current_tenant_id()
        to lodgekeeper_provisioner;
      grant execute on function app.touch_updated_at()
        to lodgekeeper_provisioner;

      grant select, insert
        on tenants,
           properties,
           users,
           user_invitations
        to lodgekeeper_provisioner;

      grant select on users, user_invitations, auth_sessions
        to lodgekeeper_runtime;
      grant update (
        display_name,
        password_hash,
        status,
        email_verified_at,
        activated_at,
        suspended_at,
        updated_at
      ) on users to lodgekeeper_runtime;
      grant update (accepted_at, revoked_at)
        on user_invitations to lodgekeeper_runtime;
      grant insert, update, delete on auth_sessions
        to lodgekeeper_runtime;
    `);
  }

  override down(): void | Promise<void> {
    this.addSql('drop table if exists auth_sessions;');
    this.addSql('drop table if exists user_invitations;');
    this.addSql('drop table if exists users;');
  }
}
