import { Migration } from '@mikro-orm/migrations';

const TENANT_SCOPED_TABLES = [
  'properties',
  'rental_policies',
  'amenities',
  'accommodation_unit_types',
  'accommodation_unit_type_rates',
  'accommodation_unit_type_amenities',
  'accommodation_units',
] as const;

export class Migration20260731191920_accommodation extends Migration {
  override up(): void | Promise<void> {
    // PostgreSQL-only infrastructure that is outside entity metadata.
    this.addSql('create extension if not exists btree_gist;');
    this.addSql('create schema if not exists app;');

    this.addSql(`
      create function app.current_tenant_id()
      returns uuid
      language sql
      stable
      set search_path = pg_catalog
      as $$
        select nullif(current_setting('app.current_tenant_id', true), '')::uuid
      $$;
    `);

    this.addSql(`
      create function app.touch_updated_at()
      returns trigger
      language plpgsql
      set search_path = pg_catalog
      as $$
      begin
        new.updated_at = statement_timestamp();
        return new;
      end
      $$;
    `);

    // Generated by MikroORM from the entity metadata.
    this.addSql(
      `create table "tenants" ("id" uuid not null default uuidv7(), "name" text not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );

    this.addSql(
      `create table "properties" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "name" text not null, "currency_code" varchar(3) not null, "timezone" text not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );
    this.addSql(
      `alter table "properties" add constraint "properties_tenant_id_id_unique" unique ("tenant_id", "id");`,
    );
    this.addSql(
      `create unique index properties_active_name_unique on properties (tenant_id, lower(btrim(name))) where archived_at is null;`,
    );

    this.addSql(
      `create table "rental_policies" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "property_id" uuid not null, "name" text not null, "kind" text not null, "duration_minutes" int null, "grace_period_minutes" int not null default 0, "check_in_time" time(0) null, "check_out_time" time(0) null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );
    this.addSql(
      `alter table "rental_policies" add constraint "rental_policies_tenant_property_id_unique" unique ("tenant_id", "property_id", "id");`,
    );
    this.addSql(
      `create unique index rental_policies_active_name_unique on rental_policies (tenant_id, property_id, lower(btrim(name))) where archived_at is null;`,
    );

    this.addSql(
      `create table "amenities" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "name" text not null, "description" text null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );
    this.addSql(
      `alter table "amenities" add constraint "amenities_tenant_id_id_unique" unique ("tenant_id", "id");`,
    );
    this.addSql(
      `create unique index amenities_active_name_unique on amenities (tenant_id, lower(btrim(name))) where archived_at is null;`,
    );

    this.addSql(
      `create table "accommodation_unit_types" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "property_id" uuid not null, "rental_policy_id" uuid not null, "name" text not null, "kind" text not null default 'room', "description" text null, "max_occupancy" int not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );
    this.addSql(
      `alter table "accommodation_unit_types" add constraint "unit_types_tenant_property_id_unique" unique ("tenant_id", "property_id", "id");`,
    );
    this.addSql(
      `create unique index unit_types_active_name_unique on accommodation_unit_types (tenant_id, property_id, lower(btrim(name))) where archived_at is null;`,
    );

    this.addSql(
      `create table "accommodation_unit_type_rates" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "property_id" uuid not null, "accommodation_unit_type_id" uuid not null, "amount_minor" bigint not null, "valid_from" date not null, "valid_to" date null, "created_at" timestamptz not null default now(), primary key ("id"));`,
    );
    this.addSql(
      `create index unit_type_rates_current_lookup on accommodation_unit_type_rates (tenant_id, accommodation_unit_type_id, valid_from desc);`,
    );

    this.addSql(
      `create table "accommodation_unit_type_amenities" ("tenant_id" uuid not null, "property_id" uuid not null, "accommodation_unit_type_id" uuid not null, "amenity_id" uuid not null, "created_at" timestamptz not null default now(), primary key ("tenant_id", "accommodation_unit_type_id", "amenity_id"));`,
    );

    this.addSql(
      `create table "accommodation_units" ("id" uuid not null default uuidv7(), "tenant_id" uuid not null, "property_id" uuid not null, "accommodation_unit_type_id" uuid not null, "code" text not null, "floor_label" text null, "display_name" text null, "notes" text null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "archived_at" timestamptz null, primary key ("id"));`,
    );
    this.addSql(
      `create unique index units_active_code_unique on accommodation_units (tenant_id, property_id, lower(btrim(code))) where archived_at is null;`,
    );

    this.addSql(
      `alter table "tenants" add constraint "tenants_name_not_blank" check (btrim(name) <> '');`,
    );
    this.addSql(
      `create trigger tenants_touch_updated_at before update on tenants for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "properties" add constraint "properties_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on delete restrict;`,
    );
    this.addSql(
      `alter table "properties" add constraint "properties_name_not_blank" check (btrim(name) <> '');`,
    );
    this.addSql(
      `alter table "properties" add constraint "properties_currency_code_format" check (currency_code ~ '^[A-Z]{3}$');`,
    );
    this.addSql(
      `alter table "properties" add constraint "properties_timezone_not_blank" check (btrim(timezone) <> '');`,
    );
    this.addSql(
      `create trigger properties_touch_updated_at before update on properties for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "rental_policies" add constraint "rental_policies_property_fk" foreign key ("tenant_id", "property_id") references "properties" ("tenant_id", "id") on delete restrict;`,
    );
    this.addSql(
      `alter table "rental_policies" add constraint "rental_policies_name_not_blank" check (btrim(name) <> '');`,
    );
    this.addSql(
      `alter table "rental_policies" add constraint "rental_policies_grace_non_negative" check (grace_period_minutes >= 0);`,
    );
    this
      .addSql(`alter table "rental_policies" add constraint "rental_policies_shape_valid" check (
        (
          kind = 'rolling_duration'
          and duration_minutes > 0
          and check_in_time is null
          and check_out_time is null
        )
        or
        (
          kind = 'calendar_night'
          and duration_minutes is null
          and check_in_time is not null
          and check_out_time is not null
        )
      );`);
    this.addSql(
      `alter table "rental_policies" add constraint "rental_policies_kind_check" check ("kind" in ('calendar_night', 'rolling_duration'));`,
    );
    this.addSql(
      `create trigger rental_policies_touch_updated_at before update on rental_policies for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "amenities" add constraint "amenities_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on delete restrict;`,
    );
    this.addSql(
      `alter table "amenities" add constraint "amenities_name_not_blank" check (btrim(name) <> '');`,
    );
    this.addSql(
      `create trigger amenities_touch_updated_at before update on amenities for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "accommodation_unit_types" add constraint "unit_types_property_fk" foreign key ("tenant_id", "property_id") references "properties" ("tenant_id", "id") on delete restrict;`,
    );
    this.addSql(
      `alter table "accommodation_unit_types" add constraint "unit_types_rental_policy_fk" foreign key ("tenant_id", "property_id", "rental_policy_id") references "rental_policies" ("tenant_id", "property_id", "id") on delete restrict;`,
    );
    this.addSql(
      `alter table "accommodation_unit_types" add constraint "unit_types_name_not_blank" check (btrim(name) <> '');`,
    );
    this.addSql(
      `alter table "accommodation_unit_types" add constraint "unit_types_max_occupancy_positive" check (max_occupancy > 0);`,
    );
    this.addSql(
      `alter table "accommodation_unit_types" add constraint "accommodation_unit_types_kind_check" check ("kind" in ('room'));`,
    );
    this.addSql(
      `create trigger accommodation_unit_types_touch_updated_at before update on accommodation_unit_types for each row execute function app.touch_updated_at();`,
    );

    this.addSql(
      `alter table "accommodation_unit_type_rates" add constraint "unit_type_rates_unit_type_fk" foreign key ("tenant_id", "property_id", "accommodation_unit_type_id") references "accommodation_unit_types" ("tenant_id", "property_id", "id") on delete restrict;`,
    );
    this.addSql(
      `alter table "accommodation_unit_type_rates" add constraint "unit_type_rates_amount_positive" check (amount_minor > 0);`,
    );
    this.addSql(
      `alter table "accommodation_unit_type_rates" add constraint "unit_type_rates_period_valid" check (valid_to is null or valid_to > valid_from);`,
    );
    this
      .addSql(`alter table "accommodation_unit_type_rates" add constraint "unit_type_rates_periods_do_not_overlap" 
        exclude using gist (
          tenant_id with =,
          accommodation_unit_type_id with =,
          daterange(valid_from, valid_to, '[)') with &&
        );`);

    this.addSql(
      `alter table "accommodation_unit_type_amenities" add constraint "unit_type_amenities_unit_type_fk" foreign key ("tenant_id", "property_id", "accommodation_unit_type_id") references "accommodation_unit_types" ("tenant_id", "property_id", "id") on update no action on delete cascade;`,
    );
    this.addSql(
      `alter table "accommodation_unit_type_amenities" add constraint "unit_type_amenities_amenity_fk" foreign key ("tenant_id", "amenity_id") references "amenities" ("tenant_id", "id") on update no action on delete restrict;`,
    );

    this.addSql(
      `alter table "accommodation_units" add constraint "units_unit_type_fk" foreign key ("tenant_id", "property_id", "accommodation_unit_type_id") references "accommodation_unit_types" ("tenant_id", "property_id", "id") on delete restrict;`,
    );
    this.addSql(
      `alter table "accommodation_units" add constraint "units_code_not_blank" check (btrim(code) <> '');`,
    );
    this.addSql(
      `alter table "accommodation_units" add constraint "units_floor_label_not_blank" check (floor_label is null or btrim(floor_label) <> '');`,
    );
    this.addSql(
      `alter table "accommodation_units" add constraint "units_display_name_not_blank" check (display_name is null or btrim(display_name) <> '');`,
    );
    this.addSql(
      `create trigger accommodation_units_touch_updated_at before update on accommodation_units for each row execute function app.touch_updated_at();`,
    );

    // PostgreSQL-only RLS policies and grants.
    this.addSql(`
      alter table tenants enable row level security;
      alter table tenants force row level security;
      create policy tenants_tenant_isolation on tenants
      using (id = app.current_tenant_id())
      with check (id = app.current_tenant_id());
    `);

    for (const table of TENANT_SCOPED_TABLES) {
      this.addSql(`
        alter table ${table} enable row level security;
        alter table ${table} force row level security;
        create policy ${table}_tenant_isolation on ${table}
        using (tenant_id = app.current_tenant_id())
        with check (tenant_id = app.current_tenant_id());
      `);
    }

    this.addSql(`
      revoke all on function app.current_tenant_id() from public;
      revoke all on function app.touch_updated_at() from public;
      grant usage on schema public, app to lodgekeeper_runtime;
      grant execute on function app.current_tenant_id()
        to lodgekeeper_runtime;
      grant execute on function app.touch_updated_at()
        to lodgekeeper_runtime;
      grant select, insert, update, delete
        on tenants,
           properties,
           rental_policies,
           amenities,
           accommodation_unit_types,
           accommodation_unit_type_rates,
           accommodation_unit_type_amenities,
           accommodation_units
        to lodgekeeper_runtime;
    `);
  }

  override down(): void | Promise<void> {
    this.addSql('drop table if exists accommodation_unit_type_rates;');
    this.addSql('drop table if exists accommodation_unit_type_amenities;');
    this.addSql('drop table if exists accommodation_units;');
    this.addSql('drop table if exists accommodation_unit_types;');
    this.addSql('drop table if exists amenities;');
    this.addSql('drop table if exists rental_policies;');
    this.addSql('drop table if exists properties;');
    this.addSql('drop table if exists tenants;');
    this.addSql('drop function if exists app.touch_updated_at();');
    this.addSql('drop function if exists app.current_tenant_id();');
    this.addSql('drop schema if exists app;');
  }
}
